### ISSUE TITLE
To compile on some Centos 6 / RHEL systems requires workarounds

### ISSUE THREAD

**Issue by rltillett** [aquaskyline/SOAPdenovo-Trans#1]
For SOAPdenovo-Trans users attempting to compile on Centos6/RHEL (and without root/admin privileges), the compiler may fail because these systems do not typically ship with the static versions of the math library `lm` or `lz`. Errors will look like this:

```
sh make.sh
../SOAPdenovo-Trans-31mer cleaning done.
/usr/bin/ld: cannot find -lz
collect2: ld returned 1 exit status
make: *** [SOAPdenovo] Error 1
```

Workaround 1) modify the ./src/Makefile & remove the -static CFLAG. 
from `CFLAGS=         -O3 -fomit-frame-pointer -static`
to `CFLAGS=         -O3 -fomit-frame-pointer`

Workaround 2) don't change the -static flag, but instead build SOAPdenovo-Trans on a system where they have privileges and can apt-get or yum install the requisite static libraries, and then move the statically-built executables to their Centos/RHEL server.

**Comment by blithe0404** [comment]
I did as you suggested and it was properly installed. However, there is another problem raised as following:
 

>$./SOAPdenovo-Trans-127mer all -s config_file -o ~/SOAPdenovo-Trans-1.04/test/output_prefix

The version 1.03: released on July 19th, 2013
With bug fixes by Chris Boursnell January 23rd, 2014

pregraph -s config_file -o /home/uqbchen4/SOAPdenovo-Trans-1.04/test/output_prefix
Cannot open config_file. Now exit to system...

> 
Can you please advise??

Thanks! Really appreciated.

**Comment by rltillett** [comment]
@blithe0404 
I hope this isn't a silly question, but does there exist a file named `config_file` in the directory/context in which you were executing the command? and did you have read-privleiges for said file?

If that was a silly question, which of my 2 workarounds did you try? and do you get the same weirdness if you try the other workaround instead?
