### ISSUE TITLE
v1.04 compilation pre-req

### ISSUE THREAD

**Issue by MDSharma** [aquaskyline/SOAPdenovo-Trans#11]
Hello,

with my initial attmepts at compiling v1.04 on CentOS Linux release 7.4.1708 (Core) x64

I was getting the following errors:
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc

These were resolved by installing the following libraries:
 glibc-static zlib-static

Just thought of mentioning it in case it comes in handy for others.

**Comment by Shellfishgene** [comment]
Thanks, helped me. Another solution is to remove the ```-static``` option from the Makefile.
