### ISSUE TITLE
Error 1 - /usr/bin/ld: unable to find-lz

### ISSUE THREAD

**Issue by TizianaS92** [aquaskyline/SOAPdenovo-Trans#13]
Hello, 
I'm having some issues while trying to install SOAPdenovo-Trans on my CentOS 7.0 system...
When I try to run the installing command 'sh make.sh' I get those errors...

https://pastebin.com/DA99f0rR

Any idea what could have happened?
Thanks in advance!

**Comment by Aspie96** [comment]
Try running the following command first:
`sudo apt-get install zlib1g-dev`

**Comment by TizianaS92** [comment]
It worked, but with:

sudo yum install zlib-static

It was able to complete the installation now! Thanks!
