### ISSUE TITLE
RPKM Calculation

### ISSUE THREAD

**Issue by MalikS10** [aquaskyline/SOAPdenovo-Trans#3]
I want to figure out why I am not able to calculate the RPKM using SOAPdenovo-trans. I used - R in my cmd , but no RPKM statistics file was created.

I appreciate the support!

**Comment by aquaskyline** [comment]
a file with suffix .RPKM.Stat will be generated by 'scaff' module.

**Comment by MalikS10** [comment]
These are the files I have in my folder:
outputGraph.agp          outputGraph.contigPosInscaff  outputGraph.kmerFreq        outputGraph.preArc           outputGraph.readOnContig  outputGraph.scafSeq
outputGraph.Arc          outputGraph.ctg2Read          outputGraph.links           outputGraph.preGraphBasic    outputGraph.readOnScaf    outputGraph.scafStatistics
outputGraph.contig       outputGraph.edge.gz           outputGraph.newContigIndex  outputGraph.readInformation  outputGraph.scaf          outputGraph.updated.edge
outputGraph.ContigIndex  outputGraph.gapSeq            outputGraph.peGrads         outputGraph.readInGap        outputGraph.scaf_gap      outputGraph.vertex

Here is my command:
SOAPdenovo-Trans-127mer all -s LF.config -o outputGraph -R > outSOAP

**Comment by aquaskyline** [comment]
In the same folder, please try to run "SOAPdenovo-Trans-127mer scaff -s LF.config -o outputGraph -R >> outSOAP"

**Comment by MalikS10** [comment]
I tried what you asked, got this error
aff: invalid option -- 's'

The version 1.03: released on July 19th, 2013
With bug fixes by Chris Boursnell January 23rd, 2014


scaff -g inputGraph [-R -S -F] [-p n_cpu -L minContigLen -t locusMaxOutput -G gapLenDiff]
  -g    <string>        inputGraph: prefix of input graph file name
  -R            (optional) output assembly RPKM statistics, [NO]
  -S    (optional)      scaffold structure exists, [NO]
  -F    (optional)      fill gaps in scaffolds, [NO]
  -p    <int>           n_cpu: number of cpu for use, [8]
  -L    <int>           minContigLen: shortest contig for scaffolding, [100]
  -t    <int>           locusMaxOutput: output the number of transcripts no more than locusMaxOutput in one locus, [5]
  -G    <int>           gapLenDiff: allowed length difference between estimated and filled gap, [50]

**Comment by aquaskyline** [comment]
try SOAPdenovo-Trans-127mer scaff -g outputGraph -R

**Comment by YinlongXie** [comment]
You can check if these files are empty or abnormal: *.scafSeq,*.peGrads,*.readOnScaf

Or you can show me (xieyl@genomics.cn) the configure file, log and err report to have a further diagnose.
