### ISSUE TITLE
1.0.4 usage suggests it's really "1.03"

### ISSUE THREAD

**Issue by mbl-jbpc-richardfox** [aquaskyline/SOAPdenovo-Trans#6]
Mildly confusing usage statement, the binaries built with the 1.0.4 code seem to suggest that they are in fact 1.03:

int main (int argc, char **argv)
{
	printf ("\nThe version 1.03: released on July 19th, 2013\n");
	printf ("With bug fixes by Chris Boursnell January 23rd, 2014\n\n");
	argc--;

**Comment by aquaskyline** [comment]
updated version number to 1.04
