### ISSUE TITLE
make.sh fails

### ISSUE THREAD

**Issue by exepulveda** [aquaskyline/SOAPdenovo-Trans#7]
I download version 1.0.4 and after executing make.sh:
[a1634120@l03 SOAPdenovo-Trans-1.0.4]$ sh make.sh 
../SOAPdenovo-Trans-31mer cleaning done.
/usr/bin/ld: cannot find -lm                               
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [SOAPdenovo] Error 1
../SOAPdenovo-Trans-127mer cleaning done.
/usr/bin/ld: cannot find -lm                               
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [SOAPdenovo] Error 1
[a1634120@l03 SOAPdenovo-Trans-1.0.4]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by whositwhatnow** [comment]
did you figure this out i am running into the same issue.

**Comment by rltillett** [comment]
okay, don’t laugh, but it turns out the issue i alluded to above is one that i wrote (and i wrote the workarounds for). ha! anyway, here: #1

**Comment by whositwhatnow** [comment]
Thanks appreciate it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
