### ISSUE TITLE
Downloaded v1.04 after compiling version still 1.03

### ISSUE THREAD

**Issue by whositwhatnow** [aquaskyline/SOAPdenovo-Trans#9]
having issues with core dumperrors and read that v1.0.4 fixed those issues.  I compiled the version from the release section and after compiling it is showing version 1.0.3 and i am running into the same errors using hte old version.  

Is there an updated source code somewhere else?  the original website still has 1.0.3

**Comment by aquaskyline** [comment]
not sure whether you are using the latest code, please `git clone` the repo or download the zip archive from the release page.

**Comment by whositwhatnow** [comment]
I am, I've done both cloned and download source.  Still shows version 1.03

The version 1.03: released on July 19th, 2013
With bug fixes by Chris Boursnell January 23rd, 2014


Usage: SOAPdenovo-Trans <command> [option]
    pregraph     construction kmer-graph
    contig       eliminate errors and output contigs
    map          map reads to contigs
    scaff        scaffolding
    all          doing all the above in turn

**Comment by whositwhatnow** [comment]
Still getting error

Segmentation fault      (core dumped) SOAPdenovo-Trans-127mer all -s

**Comment by whositwhatnow** [comment]
Did Bioconda install same version output from running app:

The version 1.03: released on July 19th, 2013
With bug fixes by Chris Boursnell January 23rd, 2014


Usage: SOAPdenovo-Trans <command> [option]
    pregraph     construction kmer-graph
    contig       eliminate errors and output contigs
    map          map reads to contigs
    scaff        scaffolding
    all          doing all the above in turn

Running app now on dataset to see if it will fail. with same error
